### ISSUE TITLE
Add stack traces to each error log

### ISSUE THREAD

**Issue by contextlimit** [phproad/phpr-framework#1]
Single most helpful module development improvement.

**Comment by snetty** [comment]
agreed, also log the IP please and add a hook so that module developers can add extra information (customer id etc.)

**Comment by daftspunk** [comment]
Need to think of a way to not pollute the error.txt file though $exception->asString() ?

**Comment by contextlimit** [comment]
Pollution is fine as long as it's agreed upon, IMO. Thus a config option. Otherwise you'd only see the stack trace in the UI (stored in DB).

**Comment by contextlimit** [comment]
Still love what we built here but gotta clean up my open issues~
