### ISSUE TITLE
AR::find_all should not require array wrapping

### ISSUE THREAD

**Issue by contextlimit** [phproad/phpr-framework#11]
I'm wondering why ID arrays have to be wrapped to work with `find_all`. 

I always remember this gotcha with `->where('id in (?), array($ids))` rather than `->where('id in (?)', $ids)` but since `find_all` calls `where`, it does this as well.

Question is, why? As far as I remember, this was just overlooked and stayed there, but now we have the chance to fix it. No other framework I know, such as Doctrine or DataMapper, do it like this. They do: `->find_all($ids)`, not `->find_all(array($ids))`.

Ref: http://o7.no/Y63PFS

**Comment by contextlimit** [comment]
I suppose to maintain backwards compatibility we could check if count($ids) == 1 and $ids[0] == array. Should be able to assume it's using the old array($ids) and we can support just normal $ids. Thoughts?

**Comment by Garbee** [comment]
If it doesn't add too much overhead then maintain compatibility. No real
reason not to unless we want to hunt down everywhere in the system using
the old method and update it.

I would like to see it simply done one-way though, keep things simple and
speedy.

**Comment by daftspunk** [comment]
Could  this have something to do with the first variable extension problem? First variable cannot be an array in extensions, but perhaps an array of an array is fine?

**Comment by contextlimit** [comment]
Still love what we built here but gotta clean up my open issues~
