### ISSUE TITLE
TIME in backend

### ISSUE THREAD

**Issue by Garbee** [phproad/phpr-framework#12]
We should be able to submit times without a seconds selection. If a seconds is not sent then :00 should be assumed by default.

**Comment by contextlimit** [comment]
+1

I think the time and datetime field should use multiple inputs/dropdowns time selection also: http://o7.no/17laRqW

Dropdown 0-24 and 0-60 with AM/PM would do it.

**Comment by Garbee** [comment]
Meh, I don't really like the separated inputs. [ptTimeSelect](http://pttimeselect.sourceforge.net/example/index.html) is my personal favorite selector right now. Nice simple UI. The only issue is you need to actually press "Set" when submitting or else it doesn't get set in the form. But that is one minor thing to overcome for a quick and simple selector.

**Comment by contextlimit** [comment]
Yah that works. :+1:  Should be able to make it auto set.

**Comment by Garbee** [comment]
This also makes DATETIME a bit better since you'd then have a single date input with a helper along with a single helper for inputting the time. Also it avoids the 24 hour thing since that adds conversion for people which many don't like to do. 

ptTimeSelect is the best I have found, although I think Chrome now ships with (or will soon) a time helper built in. Should we have supporting browsers use their built in method or override and always use our custom helper?

**Comment by daftspunk** [comment]
+1 
I'll pick up this one
