### ISSUE TITLE
mysqli or PDO over mysql functions.

### ISSUE THREAD

**Issue by Garbee** [phproad/phpr-framework#13]
The db connection and any other functions talking to the DB should be made to use the mysqli or PDO extensions since the built in mysql functions of php are depreciated as of 5.5 and will be removed in future versions.

**Comment by daftspunk** [comment]
Agree. I think in the short term we use the equivalent which is mysqli.

**Comment by contextlimit** [comment]
mysqli for the long term :+1: Support for PDO would be a nice bonus.

**Comment by Garbee** [comment]
What would PDO support offer that MySQLi wouldn't? I am not seeing anything really "must have" in the [matrix comparison](http://php.net/manual/en/mysqlinfo.api.choosing.php).

**Comment by contextlimit** [comment]
About 10 other types of databases. SQLite and Postgres most importantly. http://o7.no/12jkpOD

**Comment by Garbee** [comment]
Ah, extra DB support. So yea, long-term worth investing some time into.

**Comment by daftspunk** [comment]
+1 MySQLi

**Comment by Garbee** [comment]
Yea, thinking this over PDO is nice but mysqli is all we really need. We should keep things as simple as possible for both maintenance, documentation, and support. Going PDO allows many ways to do things which the docs most likely won't end up covering too well.

We should go mysqli and stick to it in my opinion.
