### ISSUE TITLE
get_date() shows time as well.

### ISSUE THREAD

**Issue by Garbee** [phproad/phpr-framework#19]
The get_time() method will give the time as well even though it should only return the date portion of the time.
For example:

``` php
$datetime = new Phpr_DateTime; 
echo $datetime->get_date($post->date_published);
```

Pulling a DATE type from the DB will return the right date plus 00:00:00 for the time.

**Comment by daftspunk** [comment]
get_date() returns a Phpr_DateTime object, hence the time component, would you be expecting a Phpr_Date object instead?

**Comment by Garbee** [comment]
Yes, a Phpr_Date object should be returned. The name of get_date leads me to believe that I am only getting a date from this, not any time association.

However, for the use-case where this arose I still need to use the to_long_date_format() method. So that takes care of the issue. This is also in the Phpr_DateTime class, so that can lead some credence to it returning a time of some kind, even if it is 00:00:00.

Does anyone else have any thoughts on exactly what get_date() should return with the DateTime class?
