### ISSUE TITLE
There should be a behaviour/widget for linking records together

### ISSUE THREAD

**Issue by contextlimit** [phproad/phpr-framework#21]
It keeps coming up. 

**Requirements**
- Show a button to Link them together in the toolbar
- Clicking the button shows a popup to choose a record (uses record finder).
- You can unlink them now.
- Should sync linked records in the controller's onSave (not the model's onSave or they will loop without very thought out protection but still be dangerous).
- Each model should define a method to sync the fields across. It should throw an exception in the base widget saying the inheritor has not defined it.

e.g. Edit | Delete | Link to User | Link to Map Location | Link to Profile

**Comment by daftspunk** [comment]
So this is a reverse record finder?

**Comment by contextlimit** [comment]
It's a standard for syncing record fields (take a look at the f***locator_location model).

**Comment by daftspunk** [comment]
I see

**Comment by contextlimit** [comment]
Still love what we built here but gotta clean up my open issues~
