### ISSUE TITLE
Check for Updates | Sync DB

### ISSUE THREAD

**Issue by damanic** [phproad/phpr-framework#35]
Currently there is no way to apply local update .sql .php files in your custom modules without doing a 'Force Update'. Force Update re-establishes all core modules which is not nessesary when you are running the update to apply changes to your own custom modules. 

I beleive it would be helpful to have buttons:
Check for Online Updates | Apply Local Updates | Sync DB

Check for online updates is the current popup, no changes apart from description required there. It is used to look for new releases to the core. You choose to apply online updates if found or force an update to bring your install back into line with the current release.

'Apply local update' will run through the update process without downloading anything from the online update center. 

An 'Apply local updates' button might be as simple as
 <li><?= cp_button('Local update', 'bolt', array('href'=>'javascript:;', 'onclick'=>"return $(this).phpr().post('index_on_apply_updates', { confirm: 'This will apply any updates found locally. Are you sure?' }).send()")) ?></li>

Unless anyone can think of a reason not to introduce this - I will implement.

**Comment by daftspunk** [comment]
Isn't this the same as **Sync DB**?

**Comment by damanic** [comment]
Sync DB only updates from the stucture.php. It doesnt run update scripts

**Comment by daftspunk** [comment]
+1 then. Go for it :-)

**Comment by daftspunk** [comment]
PR Complete 
https://github.com/phproad/phpr-module-admin/pull/9
