### ISSUE TITLE
Db_ActiveRecord double save, double relations

### ISSUE THREAD

**Issue by daftspunk** [phproad/phpr-framework#4]
This is a fairly deep problem. Take this scenario:

```
$joe = User::create();
$bill = User:create();

$joe->friends->add($bill);
$joe->save(); // Bill is added as Joe's friend
$joe->save(); // Bill is added as Joe's friend (again)
```

In the rare occasion there is an unique index in the join table, the error is produced:

```
MySQL error executing query: Duplicate entry '6-2' for key 'PRIMARY'
```

Need AR to flush relationships after the first save to prevent them from duplicating.

**Comment by contextlimit** [comment]
Yah this problem comes up a lot. In Doctrine I believe they have a `->reload()`, which I discussed with the wizard and he said it would be impossible with AR or something. So everyone needs to know to do this:

``` php
$joe->save(); // Bill is added as Joe's friend
$joe = $joe->find($joe->id);
$joe->save(); // Bill is added as Joe's friend (again)
```

**Comment by daftspunk** [comment]
What about
`
$joe->save(); // Bill is added as Joe's friend
$joe = $joe->reset_relations();
$joe->save(); // Bill is added as Joe's friend (again)
`
Does this work?
