### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by Garbee** [phproad/phpr-framework#7]
Currently the framework isn't using bcrypt for encrypting passwords. Since this is the best current method and the de` facto standard for any new project it should be switched. However since sites run the current encryption method there needs to be a way for them to chose to upgrade if they wish to the newer encryption method and simply have bcrypt on by default for newer installs.

**Comment by contextlimit** [comment]
:+1: 

Wanted to switch before. Let's blow this fish sky high!

**Comment by Garbee** [comment]
I think we should keep it simple and go with what comes highly recommended by many, that is [passoword_compat](https://github.com/ircmaxell/password_compat). It is an implementation of the password_hash function that is in PHP 5.5 but works with 5.3.x and up. That will be much simpler, safter, and faster to integrate compared to trying to do our own crypt.

EDIT: Also on the note of backwards compat with current sites running. It looks like we will need a config parameter so that current installs can continue using the old and insecure md5 + salt. Any new installs should default to using bcrypt.

**Comment by Garbee** [comment]
So, I have working code to use the password_compat library for Road. I'm going to try an do this in stages to give a little breathing room in case of errors.
1. Get Pull Request 6 figured out with phpr-module-admin so we reduce the code needing to be edited and keep things simple.
2. Update the Phpr_SecurityFramework class to contain a verify_password method. This will be called by passing the password and user to verify against, returning true if good or false if bad.
3. Update all module code that deals with current authentication methods and have them use the verify_password method.
4. Once the modules are updated, we will then add in the password_compat library and refactor the salted_hash and verify_passwords methods of Phpr_SecurityFramework to use password_compat (on by default in new installs via config.tpl change in installer) or the legacy method by defaulting the new config value to true.
5. Push the update and urge older install bases to update.

Any thoughts on this procedure?

**Comment by KB1RMA** [comment]
I, for one, would be in favor of putting very minimal effort into a legacy security method. In this day and age, the current MD5 + salt really isn't acceptable to be used in anything. Those users really should upgrade anyway. If the user base were larger, it would likely be something that should be considered. At this stage in the project, it seems a small price to pay. After all, it hasn't technically been "released" yet.

**Comment by Garbee** [comment]
So, it turns out with that pull request there is a slight difference that I was overlooking. Admin_User uses the salted_hash function for password lookup while Phpr_User just md5's it for lookup.

This makes doing a really smooth migration a bit more difficult. So, I'm just going to fork all the things and on-by-one submit PR's which carry out the transition in full for each repo.

**Comment by daftspunk** [comment]
What conclusion have we arrived at for this. I'm thinking a `$CONFIG['pass_encryption'] = "X";` would be best

**Comment by Garbee** [comment]
My test code uses `php $CONFIG['LEAGACY_PASSWORD_HASH']` as a boolean value. True to use it, false to use the newer method.

This would mean on install during the generation of the config.php file from the template we would need to autodetect which is supported and set the value appropriately (or possibly make it simply an actual option to keep things as simple as possible, defaulting to false of course.)
